/*
 * This file was generated by the scsynth tool, and is available for use under
 * the MIT license. More information can be found at
 * https://github.com/arminalaghi/scsynth/
 */
module MReSC_Sobel3x3_g2( //the stochastic core of an ReSC
	input [0:0] x_1, //independent copies of x_1
	input [0:0] x_2, //independent copies of x_2
	input [0:0] x_3, //independent copies of x_3
	input [0:0] x_4, //independent copies of x_4
	input [0:0] x_5, //independent copies of x_5
	input [0:0] x_6, //independent copies of x_6
	input [0:0] x_7, //independent copies of x_7
	input [0:0] x_8, //independent copies of x_8
	input [255:0] w, //Bernstein coefficients
	output reg z //output bitsream
);

	wire [0:0] sum_1; //sum of x values for mux
	assign sum_1 = x_1[0];

	wire [0:0] sum_2; //sum of x values for mux
	assign sum_2 = x_2[0];

	wire [0:0] sum_3; //sum of x values for mux
	assign sum_3 = x_3[0];

	wire [0:0] sum_4; //sum of x values for mux
	assign sum_4 = x_4[0];

	wire [0:0] sum_5; //sum of x values for mux
	assign sum_5 = x_5[0];

	wire [0:0] sum_6; //sum of x values for mux
	assign sum_6 = x_6[0];

	wire [0:0] sum_7; //sum of x values for mux
	assign sum_7 = x_7[0];

	wire [0:0] sum_8; //sum of x values for mux
	assign sum_8 = x_8[0];

	always @(*) begin
		case(sum_1)
			1'd0: case(sum_2)
				1'd0: case(sum_3)
					1'd0: case(sum_4)
						1'd0: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[0];
										1'd1: z = w[1];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[2];
										1'd1: z = w[3];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[4];
										1'd1: z = w[5];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[6];
										1'd1: z = w[7];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[8];
										1'd1: z = w[9];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[10];
										1'd1: z = w[11];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[12];
										1'd1: z = w[13];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[14];
										1'd1: z = w[15];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						1'd1: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[16];
										1'd1: z = w[17];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[18];
										1'd1: z = w[19];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[20];
										1'd1: z = w[21];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[22];
										1'd1: z = w[23];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[24];
										1'd1: z = w[25];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[26];
										1'd1: z = w[27];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[28];
										1'd1: z = w[29];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[30];
										1'd1: z = w[31];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						default: z = 0;
					endcase
					1'd1: case(sum_4)
						1'd0: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[32];
										1'd1: z = w[33];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[34];
										1'd1: z = w[35];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[36];
										1'd1: z = w[37];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[38];
										1'd1: z = w[39];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[40];
										1'd1: z = w[41];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[42];
										1'd1: z = w[43];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[44];
										1'd1: z = w[45];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[46];
										1'd1: z = w[47];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						1'd1: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[48];
										1'd1: z = w[49];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[50];
										1'd1: z = w[51];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[52];
										1'd1: z = w[53];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[54];
										1'd1: z = w[55];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[56];
										1'd1: z = w[57];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[58];
										1'd1: z = w[59];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[60];
										1'd1: z = w[61];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[62];
										1'd1: z = w[63];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						default: z = 0;
					endcase
					default: z = 0;
				endcase
				1'd1: case(sum_3)
					1'd0: case(sum_4)
						1'd0: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[64];
										1'd1: z = w[65];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[66];
										1'd1: z = w[67];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[68];
										1'd1: z = w[69];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[70];
										1'd1: z = w[71];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[72];
										1'd1: z = w[73];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[74];
										1'd1: z = w[75];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[76];
										1'd1: z = w[77];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[78];
										1'd1: z = w[79];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						1'd1: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[80];
										1'd1: z = w[81];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[82];
										1'd1: z = w[83];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[84];
										1'd1: z = w[85];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[86];
										1'd1: z = w[87];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[88];
										1'd1: z = w[89];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[90];
										1'd1: z = w[91];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[92];
										1'd1: z = w[93];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[94];
										1'd1: z = w[95];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						default: z = 0;
					endcase
					1'd1: case(sum_4)
						1'd0: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[96];
										1'd1: z = w[97];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[98];
										1'd1: z = w[99];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[100];
										1'd1: z = w[101];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[102];
										1'd1: z = w[103];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[104];
										1'd1: z = w[105];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[106];
										1'd1: z = w[107];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[108];
										1'd1: z = w[109];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[110];
										1'd1: z = w[111];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						1'd1: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[112];
										1'd1: z = w[113];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[114];
										1'd1: z = w[115];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[116];
										1'd1: z = w[117];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[118];
										1'd1: z = w[119];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[120];
										1'd1: z = w[121];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[122];
										1'd1: z = w[123];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[124];
										1'd1: z = w[125];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[126];
										1'd1: z = w[127];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						default: z = 0;
					endcase
					default: z = 0;
				endcase
				default: z = 0;
			endcase
			1'd1: case(sum_2)
				1'd0: case(sum_3)
					1'd0: case(sum_4)
						1'd0: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[128];
										1'd1: z = w[129];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[130];
										1'd1: z = w[131];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[132];
										1'd1: z = w[133];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[134];
										1'd1: z = w[135];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[136];
										1'd1: z = w[137];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[138];
										1'd1: z = w[139];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[140];
										1'd1: z = w[141];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[142];
										1'd1: z = w[143];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						1'd1: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[144];
										1'd1: z = w[145];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[146];
										1'd1: z = w[147];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[148];
										1'd1: z = w[149];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[150];
										1'd1: z = w[151];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[152];
										1'd1: z = w[153];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[154];
										1'd1: z = w[155];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[156];
										1'd1: z = w[157];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[158];
										1'd1: z = w[159];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						default: z = 0;
					endcase
					1'd1: case(sum_4)
						1'd0: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[160];
										1'd1: z = w[161];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[162];
										1'd1: z = w[163];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[164];
										1'd1: z = w[165];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[166];
										1'd1: z = w[167];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[168];
										1'd1: z = w[169];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[170];
										1'd1: z = w[171];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[172];
										1'd1: z = w[173];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[174];
										1'd1: z = w[175];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						1'd1: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[176];
										1'd1: z = w[177];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[178];
										1'd1: z = w[179];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[180];
										1'd1: z = w[181];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[182];
										1'd1: z = w[183];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[184];
										1'd1: z = w[185];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[186];
										1'd1: z = w[187];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[188];
										1'd1: z = w[189];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[190];
										1'd1: z = w[191];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						default: z = 0;
					endcase
					default: z = 0;
				endcase
				1'd1: case(sum_3)
					1'd0: case(sum_4)
						1'd0: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[192];
										1'd1: z = w[193];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[194];
										1'd1: z = w[195];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[196];
										1'd1: z = w[197];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[198];
										1'd1: z = w[199];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[200];
										1'd1: z = w[201];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[202];
										1'd1: z = w[203];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[204];
										1'd1: z = w[205];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[206];
										1'd1: z = w[207];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						1'd1: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[208];
										1'd1: z = w[209];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[210];
										1'd1: z = w[211];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[212];
										1'd1: z = w[213];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[214];
										1'd1: z = w[215];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[216];
										1'd1: z = w[217];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[218];
										1'd1: z = w[219];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[220];
										1'd1: z = w[221];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[222];
										1'd1: z = w[223];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						default: z = 0;
					endcase
					1'd1: case(sum_4)
						1'd0: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[224];
										1'd1: z = w[225];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[226];
										1'd1: z = w[227];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[228];
										1'd1: z = w[229];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[230];
										1'd1: z = w[231];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[232];
										1'd1: z = w[233];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[234];
										1'd1: z = w[235];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[236];
										1'd1: z = w[237];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[238];
										1'd1: z = w[239];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						1'd1: case(sum_5)
							1'd0: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[240];
										1'd1: z = w[241];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[242];
										1'd1: z = w[243];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[244];
										1'd1: z = w[245];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[246];
										1'd1: z = w[247];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							1'd1: case(sum_6)
								1'd0: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[248];
										1'd1: z = w[249];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[250];
										1'd1: z = w[251];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								1'd1: case(sum_7)
									1'd0: case(sum_8)
										1'd0: z = w[252];
										1'd1: z = w[253];
										default: z = 0;
									endcase
									1'd1: case(sum_8)
										1'd0: z = w[254];
										1'd1: z = w[255];
										default: z = 0;
									endcase
									default: z = 0;
								endcase
								default: z = 0;
							endcase
							default: z = 0;
						endcase
						default: z = 0;
					endcase
					default: z = 0;
				endcase
				default: z = 0;
			endcase
			default: z = 0;
		endcase
	end
endmodule
